version: '3'
services:
  back:
    build: ../back-express
    depends_on:
      - mongodb
    command: npm run create-admin prod && npm run start-prod
  react-app:
    build: ../front-next
    ports:
      - '3000:80'
    depends_on:
      - back
  mongo:
    image: mongo
